stages:
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"



plan_eks:
  stage: plan
  script:
    - cd infra/eks
    - terraform init -reconfigure
    - terraform plan -out=tfplan
  tags:
    - self-hosted
  artifacts:
    paths:
      - infra/eks/tfplan
    expire_in: 1 hour


apply_eks:
  stage: apply
  script:
    - cd infra/eks
    - terraform init -reconfigure
    - terraform apply -auto-approve tfplan
  when: manual
  needs: ["plan_eks"]
  tags:
    - self-hosted
