stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "v$CI_PIPELINE_ID"

build_backend:
  stage: build
  script:
    - docker build -t $ECR_BACKEND_REPO:$IMAGE_TAG ./backend
  tags:
    - self-hosted

build_frontend:
  stage: build
  script:
    - docker build -t $ECR_FRONTEND_REPO:$IMAGE_TAG ./frontend
  tags:
    - self-hosted

push_backend:
  stage: push
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BACKEND_REPO
    - docker push $ECR_BACKEND_REPO:$IMAGE_TAG
  tags:
    - self-hosted

push_frontend:
  stage: push
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_FRONTEND_REPO
    - docker push $ECR_FRONTEND_REPO:$IMAGE_TAG
  tags:
    - self-hosted

deploy:
  stage: deploy
  script:
    - aws eks update-kubeconfig --region us-east-2 --name chatapp-cluster
    - kubectl config use-context arn:aws:eks:us-east-2:339932683794:cluster/chatapp-cluster
    - kubectl apply -f k8s/namespace.yaml
    - kubectl apply -f k8s/mongodb-secret.yaml
    - kubectl apply -f k8s/mongodb-configmap.yaml
    - kubectl apply -f k8s/mongo-pvc.yaml
    - kubectl apply -f k8s/mongodb-deployment.yaml
    - kubectl apply -f k8s/mongodb-service.yaml
    - kubectl apply -f k8s/backend-secrets.yaml
    - kubectl apply -f k8s/backend-service.yaml
    - sed "s|IMAGE_PLACEHOLDER|$ECR_BACKEND_REPO:$IMAGE_TAG|g" k8s/deployment-backend.yaml > k8s/deployment-backend.yaml
    - kubectl apply -f k8s/backend-deployment.yaml
    - kubectl apply -f k8s/backend-hpa.yaml
    - kubectl apply -f k8s/frontend-configmap.yaml
    - kubectl apply -f k8s/frontend-service.yaml
    - sed "s|IMAGE_PLACEHOLDER|$ECR_FRONTEND_REPO:$IMAGE_TAG|g" k8s/deployment-frontend.yaml > k8s/deployment-frontend.yaml
    - kubectl apply -f k8s/frontend-deployment.yaml
    - kubectl apply -f k8s/frontend-hpa.yaml
    - kubectl apply -f k8s/frontend-ingress.yaml
    - kubectl apply -f k8s/metrics-server.yaml
  only:
    - DevOps
  tags:
    - self-hosted
