apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chat-app
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }

        location /assets/ {
            expires 1y;
            add_header Cache-Control "public";
            types {
                application/javascript js;
                text/css css;
                image/svg+xml svg;
            }
        }
    }