apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chat-app
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        include /etc/nginx/mime.types;

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }

        location /assets/ {
            add_header Cache-Control "public";
            try_files $uri =404;
        }

        types {
            application/javascript mjs js;
            text/css css;
            image/svg+xml svg;
        }
    }