apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chat-app
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }

        location /assets/ {
            add_header Cache-Control "public";
            add_header Content-Type "application/javascript" always;
            try_files $uri =404;
        }

        location ~ \.css$ {
            add_header Content-Type "text/css";
        }

        location ~ \.js$ {
            add_header Content-Type "application/javascript";
        }
    }