kind: Application 
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mongo-app
  namespace: argocd
spec:
  project: chat-app
  source: 
    repoURL: https://github.com/arpanelfranklin/full-stack_chatApp.git
    targetRevision: main
    path: k8s/database
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
